---
# Playbook to Validate VLANs with Napalm. This playbook can be used
# to validate the status of VLANs on hosts against a known good vlan list held in the state directory
# Use naplam_get_vlans.yml to create the known good vlan lists and state directory

- name: Validate VLANs using NAPALM
  hosts: "all"
  tasks:
    - name: "Ensure compliance/ directory exists"
      ansible.builtin.file:
        path: "./compliance"
        state: "directory"
        mode: "0711"
      delegate_to: "localhost"
      run_once: true
# Note this will fail if compliance fails. We only want to fail if a report
# isn't generated (example SSH failure etc.)

    - name: Check VLANs on switches against state file
      napalm_validate:
        validation_file: "./state/{{ inventory_hostname }}_vlans.yml"
      register: "vlan_report"
      failed_when: "'compliance_report' not in vlan_report"
# The above task will validate the state of the VLANs on each host against the vlan.yml file
# held in the state directory from the output from naplam_get_vlans.yml playbook which are used as "good state files"

    - name: "Print device compliance status"
      ansible.builtin.debug:
        var: "vlan_report.compliance_report.complies"

    - name: Store VLAN detailed compliance report
      ansible.builtin.copy:
        content: "{{ vlan_report | to_nice_json(indent=2) }}"
        dest: "./compliance/{{ inventory_hostname }}_vlans.json"
        mode: "0711"
...
