---
- name: "Create Data Centre Racks"
  netbox.netbox.netbox_rack:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      name: "{{ item }}"
      site: "{{ location.hq }}"
      type: "4-post cabinet"
      width: 19
      u_height: 42
      desc_units: true
  loop: ["Row1RackA", "Row1RackB"]

- name: "Create Manufacturers"
  netbox.netbox.netbox_manufacturer:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      name: "{{ item }}"
  loop: ["Cisco", "Arista"]

- name: "Create Device Types"
  netbox.netbox.netbox_device_type:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      slug: "{{ item.slug }}"
      model: "{{ item.slug }}"
      manufacturer: "{{ item.manufacturer }}"
      u_height: "{{ item.u_height }}"
      is_full_depth: true
  loop:
    - manufacturer: "Cisco"
      slug: "ISR-4451"
      u_height: 2
    - manufacturer: "Cisco"
      slug: "C9300-48T"
      u_height: 1
    - manufacturer: "Cisco"
      slug: "N9K-9372TX"
      u_height: 1
    - manufacturer: "Arista"
      slug: "DCS-7050Qx-32S"
      u_height: 1
  loop_control:
    label: "{{ item.manufacturer }} {{ item.slug }}"

- name: "Create Device Roles"
  netbox.netbox.netbox_device_role:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      name: "{{ item.name }}"
      colour: "{{ item.color }}"
  loop:
    - name: "Router"
      color: "FF000" #Red
    - name: "Switch"
      color: "000FF" #Blue
  loop_control:
    label: "{{ item.name }}"

- name: "Create Platforms (netwok OS)"
  netbox.netbox.netbox_platform:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      name: "{{ item.name }}"
      manufacturer: "{{ item.manufacturer }}"
  loop:
    - name: "ios"
      manufacturer: "Cisco"
    - name: "nxos"
      manufacturer: "Cisco"
    - name: "eos"
      manufacturer: "Arista"
  loop_control:
    label: "{{ item.manufacturer }} {{ item.name }}"

- name: "Create Devices"
  netbox.netbox.netbox_device:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      name: "{{ item.name }}"
      status: "active"
      device_type: "{{ item.device_type }}"
      device_role: "{{ item.device_role }}"
      platform: "{{ item.platform }}"
      rack: "{{ item.rack }}"
      face: "front"
      site: "{{ location.hq }}"
  loop:
    - name: "R1"
      device_type: "ISR-4451"
      device_role: "Router"
      platform: "ios"
      rack: "Row1RackA"
      postion: 1
    - name: "S2"
      device_type: "C9300-48T"
      device_role: "Switch"
      platform: "ios"
      rack: "Row1RackA"
      postion: 5
    - name: "S3"
      device_type: "N9K-9372TX"
      device_role: "Switch"
      platform: "nxos"
      rack: "Row1RackB"
      postion: 1
    - name: "S4"
      device_type: "DCS-7050Qx-32S"
      device_role: "Switch"
      platform: "eos"
      rack: "Row1RackB"
      postion: 5
...